PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab02/short_url/shurl/urls.py
from django.urls import path 
from . import views 

app_name = 'shurl'

urlpatterns = [
    path('', views.index, name='index'),
    path('shurl/<str:short_url>/', views.redirect, name='redirect'),
    # path('redirect/', views.redirect, name='redirect')
]

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab02/short_url/shurl_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shurl.urls')),
]

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab02/short_url/shurl/models.py
from django.db import models

class Shurl(models.Model):
    
    long_url = models.URLField(max_length=200)

    short_url = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.long_url} - {self.short_url}'

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab02/short_url/shurl/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Shurl
from random import choice
from string import ascii_letters, digits

def generator():
    return ''.join([choice(ascii_letters + digits) for _ in range(6)])

def index(request):
    if request.method == 'POST':
        long_url = request.POST['long_url']
        short_url = generator()
        Shurl.objects.create(long_url=long_url, short_url=short_url)
        context = {
            'new_url': Shurl.objects.all()
        }
        return render(request, 'shurl/index.html', context)
    else:
        context = {
            'new_url': Shurl.objects.all()
        }
        return render(request, 'shurl/index.html', context)

def redirect(request, short_url):
    latest_url = get_object_or_404(Shurl, short_url=short_url)
    return HttpResponseRedirect(latest_url.long_url)

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab02/short_url/shurl/templates/shurl/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shurl</title>
</head>
<body>
    <h1>URL Shortener</h1>
    <div>
        <form action="{% url 'shurl:index' %}" method="POST">
            {% csrf_token %}
            <input type="url" name="long_url" placeholder="Enter URL">
            <input type="submit" value="Enter">
        </form>
    </div>
    <div>
        {% for item in new_url %}
            <p>{{ item.long_url }} - <a href="{% url 'shurl:redirect' item.short_url %}" target='_blank'>{{ item.short_url }}</a></p>
        {% endfor %}
</body>
</html>