PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/chirp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('posts.urls')),
]

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.ListChirps.as_view(), name='home'),
    path('posts/create/', views.CreateChirp.as_view(), name='create'),
    path('posts/<int:pk>/', views.DetailChirp.as_view(), name='detail'),
    path('posts/<int:pk>/delete/', views.DeleteChirp.as_view(), name='delete'),
]

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/users/urls.py
from django.urls import path 
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.NewChirpUser.as_view(), name='signup'),
    path('<str:username>/', views.ChirperProfile.as_view(), name='profile'),
]

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    author = models.ForeignKey('auth.User', related_name='posts', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.author} - {self.created} - {self.body}'

    class Meta:
        ordering = ['-created']
    
    def get_absolute_url(self):
        return reverse('posts:detail', args=(self.pk,))

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/posts/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from django.http import HttpResponseRedirect

class ListChirps(ListView):
    model = Post
    template_name = 'home.html'

class CreateChirp(CreateView):
    model = Post
    template_name = 'create.html'
    fields = ['body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class DetailChirp(DetailView):
    model = Post 
    template_name = 'chirp_detail.html'

class DeleteChirp(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'delete_chirp.html'
    success_url = reverse_lazy('posts:home')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

class NewChirpUser(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')

class ChirperProfile(DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'user_profile'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

def user_profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    context = {'user_profile':user_profile}
    return render(request, 'profile.html', context)

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chirp</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monoton&family=Roboto:wght@100;400;700&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <section class="container">
        <hr>
        <header>
            <div class="navi-left">
                <h1><a href="{% url 'posts:home' %}">CHIRP</a></h1>
                <h3>Choose your birds wisely.</h3>
            </div>
            <nav>    
                <div class="navi-right">
                    {% if user.is_authenticated %}
                        <p>The early <a href="{% url 'users:profile' user.username %}">{{ user.username }}</a> gets the worm!</p>
                        <p><a href="{% url 'logout' %}">Logout</a></p>
                    {% else %}
                        <p><a href="{% url 'login' %}">Login</a></p>
                        <p><a href="{% url 'users:signup' %}">Join Chirp</a></p>
                    {% endif %}
                </div>
            </nav>
        </header>
        
        <main>
            <div class="create-chirps">
                {% if user.is_authenticated %}
                    
                    <p><a href="{% url 'posts:create' %}">Create Chirp</a></p>
                    
                {% endif %}
            </div>
            <div class="chirps">
                {% block content %}
                {% endblock content %}
                <br>
            </div>
        </main>
        <hr>
        <footer>
            <h6>Chirp Copyright &copy; Forever & A Day</h6>
        </footer>
    </section>
</body>
</html>

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/chirp_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="details">
        <h1><a href="{% url 'users:profile' post.author.username %}">{{ post.author.username }}</a></h1>
        <div class="detail">
            <h4><em> Chirped {{ post.created }}</em></h4>
            <p>{{ post.body }}</p>
        </div>
        {% if user == post.author %}
            <p><a href="{% url 'posts:delete' post.pk %}">Delete Chirp</a></p>
        {% endif %}
    </div>

{% endblock content %}

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/create.html
{% extends 'base.html' %}

{% block content %}

<div class='new-chirp'>
    <h2>New Chirp</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Chirp">
    </form>
</div>

{% endblock content %}

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/delete_chirp.html
{% extends 'base.html' %}

{% block content %}
    <div class="details">
        <h2>Delete Chirp</h2>
        <div class="detail">
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this Chirp?</p>
                <input type="submit" value="Delete">
            </form>
        </div>
    </div>
{% endblock content %}

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/home.html
{% extends 'base.html' %}

{% block content %}

  
    
    <div>
    {% for post in object_list %}
        <div class="post">
            <h4><a href="{% url 'users:profile' post.author.username %}">{{ post.author.username }}</a> - <a href="{% url 'posts:detail' post.pk %}">{{ post.created }}</a></h4>
            <p>{{ post.body }}</p>
        </div>
        <br>
    {% endfor %}
    </div>

{% endblock content %}

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="profile_posts">
    
        <h1>{{ user_profile.username }}</h1>
        <h6><em>Joined {{ user_profile.date_joined }}</em></h6>

        {% for post in user_profile.posts.all %}
            <div class="profile-post">
                <p>{{ post.body }}</p>
                <p><em>{{ post.created }}</em></p>
            </div>
            <br>
        {% endfor %}
    </div>

{% endblock content %}

PDX_Code_Guild/Fullstack_Bootcamp/Django/Labs/lab03/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>Sign up</h1>
    <div class="signup">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>
    </div>
{% endblock content %}